# Generated by Django 4.2.4 on 2023-08-31 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(choices=[('P', 'Pawn'), ('R', 'Rook'), ('N', 'Knight'), ('B', 'Bishop'), ('Q', 'Queen'), ('K', 'King')], max_length=1)),
                ('color', models.CharField(choices=[('B', 'Black'), ('W', 'White')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_service.piece')),
            ],
            options={
                'unique_together': {('x_coord', 'y_coord')},
            },
        ),
        migrations.CreateModel(
            name='ChessBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.CharField(choices=[('B', 'Black'), ('W', 'White')], default='W', max_length=1)),
                ('squares', models.ManyToManyField(to='game_service.square')),
            ],
        ),
    ]
